server:
  port: 9085

spring:
  application:
    name: ms-gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: ms-cuartos-service
          uri: lb://ms-cuartos-service
          predicates:
            - Path=/rooms/**
          filters:
            - name: AuthFilter

        - id: ms-reservas-service
          uri: lb://ms-reservas-service
          predicates:
            - Path=/reservations/**
          filters:
            - name: AuthFilter

        - id: ms-estudiantes-service
          uri: lb://ms-estudiantes-service
          predicates:
            - Path=/students/**
          filters:
            - name: AuthFilter

        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**
          filters: []

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8085/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
